version: '2'
services:
   zf:
     build:
       context: .
       dockerfile: Dockerfile
     volumes:
       - .:/var/www
     ports:
       - "8089:80"
     links:
      - db
      - doctrine

   db:
     image: mysql:5.6
     volumes:
       - .:/var/www/html
     environment:
       - "MYSQL_DATABASE=excel"
       - "MYSQL_USER=root"
       - "MYSQL_PASSWORD=root"
       - "MYSQL_ROOT_PASSWORD=root"
       - "MYSQL_UNIX_SOCKET=/var/run/mysqld/mysqld.sock"
     ports:
       - "33061:3306"

   doctrine:
     build:
       context: .
       dockerfile: docker/Doctrine/Dockerfile
     volumes:
       - .:/var/www