version: '2'
services:
   zf:
     build:
       context: .
       dockerfile: Dockerfile
     volumes:
       - .:/var/www
     ports:
       - "8089:80"
     links:
      - db

   db:
     image: mysql:5.7
     volumes:
       - .:/var/www/html
     environment:
       - "MYSQL_DATABASE=excel"
       - "MYSQL_USER=adserverplus"
       - "MYSQL_PASSWORD=ap++"
       - "MYSQL_UNIX_SOCKET=/var/run/mysqld/mysqld.sock"
       - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
     ports:
       - "3306"
