<?php
   if(isset($_FILES['plik'])) {
       $errors = array();
       $file_name = $_FILES['plik']['name'];
       $file_size = $_FILES['plik']['size'];
       $file_tmp = $_FILES['plik']['tmp_name'];
       $file_type = $_FILES['plik']['type'];
       $file_ext = strtolower(end(explode('.', $_FILES['plik']['name'])));

       move_uploaded_file($_FILES['plik']['tmp_name'], '/var/www/module/Application/src/UploadFile/'. $_FILES["plik"]['name']);
       // /var/www/html/ExcelToMySQL/module/Application/view
   }
?>

<html>
   <body>

      <form action = "" method = "POST" enctype = "multipart/form-data">
         <input type = "file" name = "plik" />
         <input type = "submit"/>

         <ul>
            <li>Sent file: <?php echo $_FILES['plik']['name'];  ?>
            <li>File tmp_name: <?php echo $_FILES['plik']['tmp_name']; ?>
            <li>File type: <?php echo $_FILES['plik']['type'] ?>
         </ul>

      </form>

   </body>
</html>



<dev class="col-lg-12 alert-success">

<form action = "/../ExcelToMySQL/module/Application/src/Controller/SimpleUpload.php" method="post" enctype="multipart/form-data">
    Select file to upload of simple method:
    <input type="file" name="fileToUpload" id="fileToUpload">
    <input type="submit" value="Submit" name="submit">
</form>

</dev>


<div class="col-lg-12 alert-info">
    With form ZendFramework:

<?php $form->prepare();?>
<?php echo $this->form()->openTag($form); ?>

    <div class="form-element">
        <?php $fileElement = $form->get('excel-file'); ?>
        <?php echo $this->formLabel($fileElement); ?>
        <?php echo $this->formFile($fileElement); ?>
        <?php echo $this->formElementErrors($fileElement); ?>
    </div>

    <button>Submit</button>

<?php echo $this->form()->closeTag(); ?>
</div>

<div id="uploader">
    <p>Your browser doesn't have Flash, Silverlight or HTML5 support.</p>

</div>

<script type="text/javascript">
    // Initialize the widget when the DOM is ready
    $(function() {
        $("#uploader").plupload({
            // General settings
            runtimes : 'html5,flash,silverlight,html4',
            url : "/upload",

            // Maximum file size
            max_file_size : '2mb',

            chunk_size: '1mb',

            // Resize images on clientside if we can
            resize : {
                width : 200,
                height : 200,
                quality : 90,
                crop: true // crop to exact dimensions
            },

            // Specify what files to browse for
            filters : [
                {title : "Image files", extensions : "jpg,gif,png"},
                {title : "Zip files", extensions : "zip,avi"}
                {title : "Excel files", extensions : "xls"}

            ],

            // Rename files by clicking on their titles
            rename: true,

            // Sort files
            sortable: true,

            // Enable ability to drag'n'drop files onto the widget (currently only HTML5 supports that)
            dragdrop: true,

            // Views to activate
            views: {
                list: true,
                thumbs: true, // Show thumbs
                active: 'thumbs'
            },

            // Flash settings
            flash_swf_url : 'js//plupload/js/Moxie.swf',

            // Silverlight settings
            silverlight_xap_url : 'js/plupload/js/Moxie.xap'
        });
    });
</script>