<?php
   if(isset($_FILES['plik'])) {
       $errors = array();
       $file_name = $_FILES['plik']['name'];
       $file_size = $_FILES['plik']['size'];
       $file_tmp = $_FILES['plik']['tmp_name'];
       $file_type = $_FILES['plik']['type'];
       $file_ext = strtolower(end(explode('.', $_FILES['plik']['name'])));

       move_uploaded_file($_FILES['plik']['tmp_name'], '/var/www/module/Application/src/UploadFile/'. $_FILES["plik"]['name']);
       // /var/www/html/ExcelToMySQL/module/Application/view
   }
?>

<html>
   <body>

      <form action = "" method = "POST" enctype = "multipart/form-data">
         <input type = "file" name = "plik" />
         <input type = "submit"/>

         <ul>
            <li>Sent file: <?php echo $_FILES['plik']['name'];  ?>
            <li>File tmp_name: <?php echo $_FILES['plik']['tmp_name']; ?>
            <li>File type: <?php echo $_FILES['plik']['type'] ?>
         </ul>

      </form>

   </body>
</html>

<div class="col-lg-12 alert-info">
    With form ZendFramework:

<?php $form->prepare();?>
<?php echo $this->form()->openTag($form); ?>

    <div class="form-element">
        <?php $fileElement = $form->get('excel-file'); ?>
        <?php echo $this->formLabel($fileElement); ?>
        <?php echo $this->formFile($fileElement); ?>
        <?php echo $this->formElementErrors($fileElement); ?>
    </div>

    <button>Submit</button>

<?php echo $this->form()->closeTag(); ?>
</div>
